package org.tohasan.pduxml.lib.a.apdublocktype;

import org.tohasan.pduxml.lib.a.EnumWithCode;

/**
 * author: IgorKaSan
 * date: 01.01.2018.
 */
public enum ApduBlockType implements EnumWithCode {
    INITIATE_REQUEST(0x01),
    READ_REQUEST(0x05),
    WRITE_REQUEST(0x06),
    INITIATE_RESPONSE(0x08),
    READ_RESPONSE(0x0C),
    WRITE_RESPONSE(0x0D),
    CONFIRMED_SERVICE_ERROR(0x0E),
    DATA_NOTIFICATION(0x0F),
    UNCONFIRMED_WRITE_REQUEST(0x16),
    INFORMATION_REPORT_REQUEST(0x18),
    GLO_INITIATE_REQUEST(0x21),
    GLO_READ_REQUEST(0x25),
    GLO_WRITE_REQUEST(0x26),
    GLO_INITIATE_RESPONSE(0x28),
    GLO_READ_RESPONSE(0x2C),
    GLO_WRITE_RESPONSE(0x2D),
    GLO_CONFIRMED_SERVICE_ERROR(0x2E),
    GLO_UNCONFIRMED_WRITE_REQUEST(0x36),
    GLO_INFORMATION_REPORT_REQUEST(0x38),
    DED_INITIATE_REQUEST(0x41),
    DED_READ_REQUEST(0x45),
    DED_WRITE_REQUEST(0x46),
    DED_INITIATE_RESPONSE(0x48),
    DED_READ_RESPONSE(0x4C),
    DED_WRITE_RESPONSE(0x4D),
    DED_CONFIRMED_SERVICE_ERROR(0x4E),
    DED_UNCONFIRMED_WRITE_REQUEST(0x56),
    DED_INFORMATION_REPORT_REQUEST(0x58),
    ASSOCIATION_REQUEST(0x60),
    ASSOCIATION_RESPONSE(0x61),
    RELEASE_REQUEST(0x62),
    RELEASE_RESPONSE(0x63),
    GET_REQUEST(0xC0),
    SET_REQUEST(0xC1),
    EVENT_NOTIFICATION_REQUEST(0xC2),
    ACTION_REQUEST(0xC3),
    GET_RESPONSE(0xC4),
    SET_RESPONSE(0xC5),
    ACTION_RESPONSE(0xC7),
    GLO_GET_REQUEST(0xC8),
    GLO_SET_REQUEST(0xC9),
    GLO_ACTION_REQUEST(0xCB),
    GLO_GET_RESPONSE(0xCC),
    GLO_SET_RESPONSE(0xCD),
    GLO_ACTION_RESPONSE(0xCF),
    DED_GET_REQUEST(0xD0),
    DED_SET_REQUEST(0xD1),
    DED_EVENT_NOTIFICATION_REQUEST(0xD2),
    DED_ACTION_REQUEST(0xD3),
    DED_GET_RESPONSE(0xD4),
    DED_SET_RESPONSE(0xD5),
    DED_ACTION_RESPONSE(0xD7),
    EXCEPTION_RESPONSE(0xD8),
    ACCESS_REQUEST(0xD9),
    ACCESS_RESPONSE(0xDA),
    GENERAL_GLO_CHIPHERING(0xDB),
    GENERAL_DED_CHIPHERING(0xDC),
    GENERAL_CHIPHERING(0xDD),
    GENERAL_SIGNING(0xDF),
    GENERAL_BLOCK_TRANSFER(0xE0),
    DATA_BLOCK_RESULT(0xFF);

    private int code;

    ApduBlockType(int code) {
        this.code = code;
    }

    public int getCode() {
        return this.code;
    }
}
